### PR TITLE
CorineLandCoverCoordModifier

### PR DESCRIPTION
**Pull request by tschlenther**
added population getter

### CODE REVIEW

**Comment by tschlenther** [comment]
do not know how to trigger the travis build status report. the build was successful some hours ago

**Comment by sebhoerl** [comment]
Seems to be the same in #950 and I had the same yesterday in the DMC repository... it seems the old interaction with Github doesn't work anymore properly with those push statuses, but instead they advised on travis-ci.com (not travis-ci.org) to switch to the Github Checks API. Unfortunately, this doesn't work on travis-ci.org, but it is possible to migrate the repository.

It took me a couple of hours yesterday, so here the short version :)
- Whoever is responsible for the matsim-org repository needs to log in to travis-ci.org
- There is a big button to "migrate" repositories to travis-ci.com , there you need to choose the matsim-org organization
- After 5 minutes the repositories show up on travis-ci.com (without migration they are not there, because they are already on travis-ci.org)
- On travis-ci.com go to Settings -> matsim-libs -> Github Apps integration -> "Activate" and follow the steps
- You can then go to the Dashboard on Travis and find the matsim-libs repository, go to one of the recent PRs or branches and click "Rebuild". Once finished Github will get a message about that through the Checks API

Somehow these steps I had to find on my own, the next ones are already documented on several issues from Travis:
- Now go to matsim-libs repository on Github -> Settings -> Branches -> Protected Branches and there you find the push/pull checks setion, which currently contains "continuous-integration/travis-ci/push" (remove it), but there should now also be a new one for the Checks API through Travis (activate it)
- For the retriggered build Github should now know that it has passed, for the other PRs we probably need to re-trigger them, but maybe it also gets detected automatically :)

**Comment by tschlenther** [comment]
Thank you @sebhoerl .

This feels to me like some admin for matsim-org should do this, and not me..
@kainagel what is your opinion on migrating?

**Comment by kainagel** [comment]
https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Pull request merged**
