### PR TITLE
run travis only for PRs coming from forks

### PR DESCRIPTION
**Pull request by michalmac**
I suggest we only run travis for external PRs. Or maybe there are some other ideas?

### CODE REVIEW

**Comment by michalmac** [comment]
Not really necessary after this change: https://github.com/matsim-org/matsim-libs/pull/1266#issuecomment-734835692

**Comment by mrieser** [comment]
Thanks Michał for all your work with the build systems!

Considering Travis provides a limited number of minutes (1000), and GitHub actions are also limited (I think 2000 minutes per month), would it make sense to distribute the builds, e.g. building branches on GitHub Actions, building PRs on Travis?

Just a thought...

**Comment by michalmac** [comment]
Yes, I was thinking about maintaining travis is a smaller scale (e.g. builds for external PRs or pushes to master, or pushes to master executed on Windows as appveyor is very limited and does not run ITs). Also to have a backup solution.

I am not 100% sure, but to me it looks like the free 2000 min/month is only for private repos. Open-source is fully free (at least now). Maybe I am wrong? Looking at my personal billing I see 0 min used so far. How does it look for the matsim organisation? (I do not have access there:-/ )

**Comment by mrieser** [comment]
Not sure how this "Free for public repos" should be interpreted. We'll see... I gave you additional rights, so you should be able to see it as well now.

**Comment by michalmac** [comment]
> I gave you additional rights, so you should be able to see it as well now.

🎉
Thanks a lot!

**Comment by kainagel** [comment]
Pls let me re-iterate that I read the travis blog such that we can apply, as an open source project, for more hours.  They also say there that one could apply for a number of regularly granted hours (e.g. per month).  I am not against splitting the work so we have a fallback option, but if "running out of build hours" is the main driver, then applying for more hours should be attempted.

**Comment by michalmac** [comment]
Something that actually convinced me to try out GH Actions was the advertised 20 parallel jobs (5 parallel jobs was a bottleneck from time to time). Otherwise I would also opt for applying for more credits.

**Comment by michalmac** [comment]
The situation with travis is a bit messy. Currently, the builds are not performed. According to https://devclass.com/2020/11/25/travis-ci-open-source-engagement/:
> Though renewable amounts are mentioned, the process looked a bit tedious as it has to be repeated every time the credit is exhausted."

Co I am closing this PR for the time being.

**Pull request closed without merging**
