### PR TITLE
Make latest endTime configurable in TripPlanMutateTimeAllocation

### PR DESCRIPTION
**Pull request by marecabo**
Currently, the `TripPlanMutateTimeAllocation` class limits activities' durations to 24 hours. This change allows for configuring the latest endTime to a custom value (e.g., 30 hours). 24h still remains the default.

### CODE REVIEW

**Comment by Janekdererste** [comment]
I would think that this should have a unit test. Would you mind adding one?

**Comment by marecabo** [comment]
Sure, I can give it a try some time this week.

**Comment by marecabo** [comment]
@Janekdererste Added a test for the latestEndTime argument.

**Comment by Janekdererste** [comment]
> @Janekdererste I added a test for the latestEndTime argument.

Looks good thank you. Merging this PR.

**Pull request merged**
