### PR TITLE
Switch to patched JOGL version

### LINKED ISSUE #972: OTFVis clashes with new mac OS
When using OTFVis (with or without signals) the Java application terminates at the moment just before creating the OTFVis window (after the simulation started) with the following exception:

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff3460a8ab __exceptionPreprocess + 250
> 	1   libobjc.A.dylib                     0x00007fff6a6e2805 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff3463330c -[NSException raise] + 9
> 	3   AppKit                              0x00007fff31783538 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
> 	4   AppKit                              0x00007fff3176aed5 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
> 	5   AppKit                              0x00007fff3176a947 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
> 	6   libnativewindow_macosx.jnilib       0x0000000131da23fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
> 	7   ???                                 0x000000011bec0c90 0x0 + 4763421840
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> 
> The simulation did not run properly. Error/Exit code: 134

The problem seems to lie in the fact that on new mac OS windows can only be generated out of the [main thread](https://trac.macports.org/ticket/58794). Does anybody know how to start OTFVis from the main thread?
Maybe @michaz or @Janekdererste ?

On Windows or older Mac versions this problem does not occur...

This problem is somehow urgent because it affects teaching...

### PR DESCRIPTION
**Pull request by michaz**
Fixes #972. I uploaded the patched JOGL version, as discussed in #972, to our Bintray, and switched OTFVis to that version.

As it's a bit messy to do this since it uses the Maven classifier feature for the different platform versions, here is the command line for the native binary JARs (starting from the cloned web site as suggested in #972). Use this if we want to repeat this for another version, or add more platform JARs such as AMD (since I don't know how to build the JAR that holds all of the platform JARs):

```
mvn deploy:deploy-file -Durl="https://api.bintray.com/maven/matsim/matsim/JOGL/;publish=1" \
                       -DrepositoryId=matsim \
                       -Dfile=jogamp.org/deployment/archive/master/gluegen_937-joal_660-jogl_1506-jocl_1147/jar/jogl-all-natives-windows-i586.jar \
                       -DgroupId=org.jogamp.jogl \   
                       -DartifactId=jogl-all \      
                       -Dversion=2.4.0-matsim-1 \
                       -Dpackaging=jar \                                    
                       -DgeneratePom=false -Dclassifier=natives-windows-i586

mvn deploy:deploy-file -Durl="https://api.bintray.com/maven/matsim/matsim/JOGL/;publish=1" \
                       -DrepositoryId=matsim \
                       -Dfile=jogamp.org/deployment/archive/master/gluegen_937-joal_660-jogl_1506-jocl_1147/jar/gluegen-rt-natives-windows-i586.jar \
                       -DgroupId=org.jogamp.gluegen \
                       -DartifactId=gluegen-rt \
                       -Dversion=2.4.0-matsim-1 \
                       -Dpackaging=jar \
                       -DgeneratePom=false -Dclassifier=natives-windows-i586
```

Change the platform identifier in two places: Filename and classifier.

When uploading the main JARs (e.g. for a new version), remove the last line (POM should be generated, and no classifier, since it's the main JAR).

### CODE REVIEW

**Comment by kainagel** [comment]
Very nice, thanks a lot @michaz .

I just tried from a freshly cloned matsim-example-project, and if I add the corresponding lines into its pom.xml, it runs otfvis as it should without having to add the native library.   

I just set it to automerge in the assumption that this is correct; please remove label if this is not what you want.

**Comment by michalmac** [comment]
> I just set it to automerge in the assumption that this is correct; please remove label if this is not what you want.

You need to update the branch to run the new CI (the config file is not in).

**Comment by michaz** [comment]
@michalmac Like this? (Haven't done this in a while...)

**Comment by michalmac** [comment]
> @michalmac Like this? (Haven't done this in a while...)

Yep :-)

But I see it hasn't got auto-merged. Will look into this issue.

**Comment by michalmac** [comment]
Now it worked. First, the branch got auto-updated and then, auto-merged.

**Comment by vsp-gleich** [comment]
Some remark: I think on the long term we also need amd even for some Intel laptops.

For me on ubuntu OTFVis did not work after this PullRequest. In gluegen-rt:2.4.0-matsim-1 there is PlatformPropsImpl.class with a weird switch case (lines 233  and 263-265 in the decompiled IntelliJ view):
`switch(cpuType) {
...
        case X86_64:
            var5 = "amd64";
            break;
...}`
So my Intel cpu is mapped to amd64 for which the gluegen-rt and jogl libraries are missing.

Adding the amd version as global library in IntelliJ as suggested in #972 solved it for me. But it would be nice if it could run out of the box again on the long run. If waiting for the 2.4.0 release solves the issue that's fine with me.

**Comment by michaz** [comment]
Will add the AMD version, no problem.

**Comment by vsp-gleich** [comment]
> Will add the AMD version, no problem.

Thank you @michaz :+1: !

**Pull request merged**
