### PR TITLE
Migrate from Java 17 to 21

### PR DESCRIPTION
**Pull request by EwoutH**
Java 21 LTS has now been release for 6 months, which may be a good time to see if we can start upgrading to Java 21. This PR tests that by updating the `pom.xml` and the GitHub Actions workflows to use Java 21 LTS instead of Java 17 LTS.

The previous Java upgrade was done and discussed here:
- #2043

Potentially interesting articles:

- [Upgrading From Java 17 To 21: All You Need To Know](https://nipafx.dev/road-to-21-upgrade/)
- [What’s New Between Java 17 and Java 21?](https://mydeveloperplanet.com/2023/11/01/whats-new-between-java-17-and-java-21/)

New features in JDK 18, 19, 20 and 21 are:

> #### [JDK 18](https://openjdk.org/projects/jdk/18/)
> - 400:	[UTF-8 by Default](https://openjdk.org/jeps/400)
> - 408:	[Simple Web Server](https://openjdk.org/jeps/408)
> - 413:	[Code Snippets in Java API Documentation](https://openjdk.org/jeps/413)
> - 416:	[Reimplement Core Reflection with Method Handles](https://openjdk.org/jeps/416)
> - 417:	[Vector API (Third Incubator)](https://openjdk.org/jeps/417)
> - 418:	[Internet-Address Resolution SPI](https://openjdk.org/jeps/418)
> - 419:	[Foreign Function & Memory API (Second Incubator)](https://openjdk.org/jeps/419)
> - 420:	[Pattern Matching for switch (Second Preview)](https://openjdk.org/jeps/420)
> - 421:	[Deprecate Finalization for Removal](https://openjdk.org/jeps/421)
> 
> #### [JDK 19](https://openjdk.org/projects/jdk/19)
> - 405:	[Record Patterns (Preview)](https://openjdk.org/jeps/405)
> - 422:	[Linux/RISC-V Port](https://openjdk.org/jeps/422)
> - 424:	[Foreign Function & Memory API (Preview)](https://openjdk.org/jeps/424)
> - 425:	[Virtual Threads (Preview)](https://openjdk.org/jeps/425)
> - 426:	[Vector API (Fourth Incubator)](https://openjdk.org/jeps/426)
> - 427:	[Pattern Matching for switch (Third Preview)](https://openjdk.org/jeps/427)
> - 428:	[Structured Concurrency (Incubator)](https://openjdk.org/jeps/428)
> 
> #### [JDK 20](https://openjdk.org/projects/jdk/20)
> - 429:	[Scoped Values (Incubator)](https://openjdk.org/jeps/429)
> - 432:	[Record Patterns (Second Preview)](https://openjdk.org/jeps/432)
> - 433:	[Pattern Matching for switch (Fourth Preview)](https://openjdk.org/jeps/433)
> - 434:	[Foreign Function & Memory API (Second Preview)](https://openjdk.org/jeps/434)
> - 436:	[Virtual Threads (Second Preview)](https://openjdk.org/jeps/436)
> - 437:	[Structured Concurrency (Second Incubator)](https://openjdk.org/jeps/437)
> - 438:	[Vector API (Fifth Incubator)](https://openjdk.org/jeps/438)
> 
> #### [JDK 21](https://openjdk.org/projects/jdk/21/)
> - 430:	[String Templates (Preview)](https://openjdk.org/jeps/430)
> - 431:	[Sequenced Collections](https://openjdk.org/jeps/431)
> - 439:	[Generational ZGC](https://openjdk.org/jeps/439)
> - 440:	[Record Patterns](https://openjdk.org/jeps/440)
> - 441:	[Pattern Matching for switch](https://openjdk.org/jeps/441)
> - 442:	[Foreign Function & Memory API (Third Preview)](https://openjdk.org/jeps/442)
> - 443:	[Unnamed Patterns and Variables (Preview)](https://openjdk.org/jeps/443)
> - 444:	[Virtual Threads](https://openjdk.org/jeps/444)
> - 445:	[Unnamed Classes and Instance Main Methods (Preview)](https://openjdk.org/jeps/445)
> - 446:	[Scoped Values (Preview)](https://openjdk.org/jeps/446)
> - 448:	[Vector API (Sixth Incubator)](https://openjdk.org/jeps/448)
> - 449:	[Deprecate the Windows 32-bit x86 Port for Removal](https://openjdk.org/jeps/449)
> - 451:	[Prepare to Disallow the Dynamic Loading of Agents](https://openjdk.org/jeps/451)
> - 452:	[Key Encapsulation Mechanism API](https://openjdk.org/jeps/452)
> - 453:	[Structured Concurrency (Preview)](https://openjdk.org/jeps/453)

### CODE REVIEW

**Comment by EwoutH** [comment]
All checks pass!

@michalmac, since you lead the migration from Java 11 to 17, could you give this PR a review?

**Review by michalmac — COMMENTED** [review]
Thanks! Looks good to me.

This PR means that the upcoming yearly release will require Java 21. I cannot say if this is good or not for teaching matsim. If not, we should wait out with merging until the yearly release is out. @kainagel what is your opinion?

This change will need to get propagated to dependant repos. I do not think this is an issue.

**Comment by michalmac** [comment]
Any 👍 or 👎 on merging this PR now?

**Comment by rakow** [comment]
Our server infrastructure does not have java 21 installed at the moment. Please wait until we had time to switch. I guess others will also need time to adapt.

**Comment by EwoutH** [comment]
Maybe we can establish a target date to switch to Java 21? With who should we coordinate/communicate about this?

**Comment by Janekdererste** [comment]
We could wait until after the yearly release (end of March) and then switch java versions on the development branch. This way, downstream projects only have to switch versions if they depend on a more recent MATSim version than the next release. This would save us from switching many downstream projects at once. 

Downstream projects can always use more recent Java versions than what their dependencies require, so there is no time pressure from that side. 

In the matsim-libs project, we would have the new version available in approximately six weeks.

**Comment by EwoutH** [comment]
Switching after the yearly release sounds reasonable. No specific reason, just seemed about time.

**Comment by paulheinr** [comment]
> Our server infrastructure does not have java 21 installed at the moment. Please wait until we had time to switch. I guess others will also need time to adapt.

Java 21 is now installed on the math cluster. But I agree, let's switch after the release.

**Comment by EwoutH** [comment]
An argument for switching before could be that Java 21 is supported for two more years over Java 17, making simulations built now be supported longer and possible future migrations easier. And it's nice to be able to use the latest features when developing.

I think the main question is, if there's enough time to properly test it before the stable release.

**Comment by michalmac** [comment]
> An argument for switching before could be that Java 21 is supported for two more years over Java 17, making simulations built now be supported longer and possible future migrations easier. And it's nice to be able to use the latest features (okay, not the very latest, because JDK 22 just released, but still), when developing.

It works a bit different. By setting the Java version to 17, we mean the bytecode will be built against version 17 (Java 17 language + public API). It can be run on any JDK 17+.

**Comment by paulheinr** [comment]
Since the new release is published, should we now switch to java 21?

**Comment by Janekdererste** [comment]
> Since the new release is published, should we now switch to java 21?

I don't see why not. Who wants to do this? We then have to migrate downstream projects as well, in case they are using recent matsim versions

**Comment by paulheinr** [comment]
Since the original PR was created from a forked repository, I created a new one: #3238

**Comment by EwoutH** [comment]
If (still) necessary I can rebase this branch.

**Pull request closed without merging**
