### PR TITLE
Fix location contrib WIP

### PR DESCRIPTION
**Pull request by kainagel**
can now handle activities with a duration instead of  an endTime
also the route to and from the changed activity is now calculated correctly

### CODE REVIEW

**Comment by mdziakowski** [comment]
> todo
can now handle activities with a duration instead of  an endTime
also the route to and from the changed activity is now calculated correctly

**Comment by kainagel** [comment]
I think that MD did not continue on this PR, but created #831 instead.

**Comment by ikaddoura** [comment]
@mdziakowski can you please resolve the conflicts, thanks!

**Comment by mdziakowski** [comment]
see pull request
Replace trip to legs in location choice contrip #895

**Pull request closed without merging**
