### PR TITLE
LAST CALL FOR 24.0!!!!!!!!!

### PR DESCRIPTION
**Pull request by Janekdererste**
It's release time. Merge things you want to have in the 24.0 release! Everything which should be in the release must be merged into the 24.x branch.

Merges into master are not part of the release after #3209 is merged. 

If you don't care, simply merge into master as always.

Issue for the release process: #2844

### CODE REVIEW

**Comment by kainagel** [comment]
Hello, shouldn't we perhaps call it 2024.0 (instead of 24.0)?  Then it's firstly clear that we haven't skipped a few versions, and secondly that we mean the year.  Or vice versa. :-)

**Comment by kainagel** [comment]
For my, `hybridsim` does not compile.  I already had that problem with some of you before my easter break.  It seems that other people have the same problem, and everybody has individual recipes to work around it.  Could that please be resolved before the release?

**Comment by Janekdererste** [comment]
> For my, hybridsim does not compile.

Both, the CI build and my local build seem to compile fine. What exactly is the problem?

When I execute `mvn clean install -DskipTests -U` I receive the following result:

```
[INFO] Reactor Summary for MATSim-All 25.0-SNAPSHOT:
[INFO] 
[INFO] MATSim-All ......................................... SUCCESS [  0.211 s]
[INFO] MATSim Examples .................................... SUCCESS [  0.917 s]
[INFO] MATSim ............................................. SUCCESS [ 10.039 s]
[INFO] MATSim Benchmark ................................... SUCCESS [  0.211 s]
[INFO] MATSim-Contrib ..................................... SUCCESS [  0.115 s]
[INFO] matrixbasedptrouter ................................ SUCCESS [  0.426 s]
[INFO] roadpricing ........................................ SUCCESS [  0.486 s]
[INFO] analysis ........................................... SUCCESS [  0.604 s]
[INFO] accessibility ...................................... SUCCESS [  0.980 s]
[INFO] accidents .......................................... SUCCESS [  0.387 s]
[INFO] otfvis ............................................. SUCCESS [  0.822 s]
[INFO] osm ................................................ SUCCESS [  0.632 s]
[INFO] SUMO Integration ................................... SUCCESS [  0.503 s]
[INFO] emissions .......................................... SUCCESS [  1.385 s]
[INFO] noise .............................................. SUCCESS [  0.600 s]
[INFO] freight ............................................ SUCCESS [  1.040 s]
[INFO] application ........................................ SUCCESS [  1.485 s]
[INFO] common ............................................. SUCCESS [  0.501 s]
[INFO] ev ................................................. SUCCESS [  0.555 s]
[INFO] dvrp ............................................... SUCCESS [  0.943 s]
[INFO] drt ................................................ SUCCESS [  1.154 s]
[INFO] taxi ............................................... SUCCESS [  0.657 s]
[INFO] av ................................................. SUCCESS [  0.481 s]
[INFO] bicycle ............................................ SUCCESS [  0.507 s]
[INFO] cadytsIntegration .................................. SUCCESS [  0.466 s]
[INFO] carsharing ......................................... SUCCESS [  0.655 s]
[INFO] commercialTrafficApplications ...................... SUCCESS [  0.603 s]
[INFO] decongestion ....................................... SUCCESS [  0.408 s]
[INFO] Discrete Mode Choice ............................... SUCCESS [  0.568 s]
[INFO] Informed Mode Choice ............................... SUCCESS [  1.040 s]
[INFO] multimodal ......................................... SUCCESS [  0.439 s]
[INFO] parking ............................................ SUCCESS [  0.655 s]
[INFO] minibus ............................................ SUCCESS [  0.794 s]
[INFO] signals ............................................ SUCCESS [  0.987 s]
[INFO] vsp ................................................ SUCCESS [  3.324 s]
[INFO] SimWrapper ......................................... SUCCESS [  1.246 s]
[INFO] drt-extensions ..................................... SUCCESS [  1.795 s]
[INFO] freightreceiver .................................... SUCCESS [  0.537 s]
[INFO] hybridsim .......................................... SUCCESS [  3.291 s]
[INFO] integration ........................................ SUCCESS [  0.385 s]
[INFO] locationchoice ..................................... SUCCESS [  0.642 s]
[INFO] protobuf ........................................... SUCCESS [  1.915 s]
[INFO] pseudosimulation ................................... SUCCESS [  0.477 s]
[INFO] railsim ............................................ SUCCESS [  0.537 s]
[INFO] sbb-extensions ..................................... SUCCESS [  0.455 s]
[INFO] matsim-sharing ..................................... SUCCESS [  0.505 s]
[INFO] simulatedannealing ................................. SUCCESS [  0.406 s]
[INFO] small-scale-traffic-generation ..................... SUCCESS [  1.073 s]
[INFO] socnetsim .......................................... SUCCESS [  1.048 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.040 s
[INFO] Finished at: 2024-04-12T08:13:07+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by kainagel** [comment]
I was on a branch where it did not work and didn't notice that I was on that branch, sorry.

**Comment by billyc** [comment]
@Janekdererste  where is the simwrapper contrib? Also needs to be in there, how can I add it to the PR?

**Pull request closed without merging**
