### PR TITLE
remove maven source plugin from freight

### PR DESCRIPTION
**Pull request by luchengqi7**
Hello Michal, 

I had a build error (see my previous email) with the matsim-lib (the freight module, which I have not touched before). I tried different methods to solve it. The build error was finally solved after I deleted one line in the pom file (see the commit). I guess that line is the reason for the build error, but I'm not sure. Could you have a look? Thanks!

### CODE REVIEW

**Review by michalmac — APPROVED** [review]
👍 

I would even remove the whole maven-source-plugin section (+ some old commented lines 19-31) to use the "contribs defaults" and thus keep things simple.

**Comment by luchengqi7** [comment]
Hi Michal,

I have found another thing that we may need to make some changes. 

Perhaps it is a good idea to split the time bin size with the rebalance interval. For Adaptive real time rebalancing strategy, the time bin size and the rebalance interval are unrelated. If the time bin size is too small, there can be some problem. As a  result. a temporary solution of adding a "Math.max" operation is used here. We can have a disucssion for a permanant solution.

**Comment by luchengqi7** [comment]
Sorry, I should split these two changes into two different pull request. But the checking for the first one has not yet finished, so I just add another commit to this pull requests.

**Review by michalmac — CHANGES_REQUESTED** [review]
The main problem with `Math.max(drtCfg.getRebalancingParams().get().getInterval(), 1800);` is that it is a hidden workaround. Some algorithms will be aware of that, some not. I suggest to do it at the API level. Here is my suggestion:
- make the time bin independent on the rebalancing interval, as you pointed out (BTW. it does not need to go into a config group now)
- change `ZonalDemandEstimator.getExpectedDemandForTimeBin(double time)` to `getExpectedDemand(double fromTime, double toTime)` so that the rebalancing algorithm (1) knows what it gets, and (2) can get what it actually needs (different algorithms may work with different planning horizons)

So my suggestion is to drop the last commit and improve the `ZonalDemandEstimator` API in a separate PR.

**Comment by luchengqi7** [comment]
Remove the maven source plug in. The plug in was causing build error in Windows operating system. Removal of the source plug in solve the build error. The other changes in this commit does not belong to this topic and therefore will be moved to other pull requests.

**Comment by tschlenther** [comment]
> 
> 
> Hi,
> what is the reason to have demand aggregate time bin size to at least half an hour?
> In our study, we saw that w larger aggregates perform better in most cases, but i do not really see why we would require a minimum other than runtime reasons..

oh sorry, i saw the commit isolated before i saw this PR. Michal has presented a clean way to handle that, i support it. Never mind my comment above. Sorry

**Pull request merged**
