### PR TITLE
build: introduce weekly code coverage for matsim core

### PR DESCRIPTION
**Pull request by michalmac**
The report is created by jacoco and then uploaded to CodeCov.

For testing purposes, the workflow is triggered on pushing to master. Later on we will switch to a weekly schedule.

### CODE REVIEW

**Comment by michalmac** [comment]
Here you can find the coverage reports: https://codecov.io/gh/matsim-org/matsim-libs. You can explore them using the sunburst chat or just by navigating the directory tree.

**Comment by kt86** [comment]
Very nice! Thanks a lot, @michalmac! 

Do you plan to also introduce it for the contribs? (When we see, that it functions well for matism-core)
I think that may also help us to see some lacks in testing and may help top improve it...
Or are there some restrictions or reasons for not doing it?

PS: I also like the batch for it (and the other workflows) on the Readme page.

**Comment by michalmac** [comment]
Thanks @kt86 

Good question. Adding it for all modules would require some additional work, but nothing blocks it. I was not sure if we really need/use code coverage for contribs. If yes, I can add it later. Right now I want to move all critical build pipelines from Jenkins to GH Actions so we can migrate to Java 17.

**Comment by kt86** [comment]
Sounds good. 

If we really "need" it?  I don't know!
But if we have it, we can have a look at it and _maybe_ improve the coverage incrementally... (and maybe @kainagel forces us, to do so - at least for the more frequently used contribs). 
Without that information, we will  (imo) _never_ do so.

**Comment by michalmac** [comment]
How we test matsim would be an interesting topic for a session during a developer meeting. Specifically, high coverage is good, but maybe should not be one of the main goals for writing tests. For instance, there are many tests that just run some matsim contribs to make sure they complete without an error, but without actually checking the output. Such tests may pump up the coverage, but at the same time add a little value to the software quality.

**Comment by Janekdererste** [comment]
I don't think there is much added value for the contribs. Usually they are maintained by one or few people. If you want to check on your coverage, you can also do that in your IDE already.

**Pull request merged**
