### PR TITLE
fix: warn for parallell links in OneToManyPathCalculator

### PR DESCRIPTION
**Pull request by sebhoerl**
Currently, there is a comment in `OneToManyPathCalculator` that already explains that having parallel links (same start and end node) may produce unexpected results when reconstructing the link sequence (see `constructLinkSequence`). 

Yesterday, I was debugging timing issues in DRT where I had a scenario in which I never managed to get the timing 100% congruent between insertion/scheduling and the simulation. After digging for several hours, I arrived at the comment in `OneToManyPathCalculator` so I thought it might be useful to have a check and a warning about the issue :)

### CODE REVIEW

**Comment by sebhoerl** [comment]
Actually, it might make sense to move this further upstream, what do you think @michalmac? The closest `public` access point to this seems to be `OneToManyPathSearch.createSearch`. To avoid multiple verifications in DRT, it would probably make sense to have the check in `MultiInsertionDetourPathCalculator`, but then individual users of the class won't see the warning.

**Comment by sebhoerl** [comment]
It might make sense to add `new NetworkSegmentDoubleLinks().run(subnetwork);` to `DvrpModeRoutingNetworkModule` if we have `useModeFilteredSubnetwork=true`

**Comment by sebhoerl** [comment]
Plus, I just noticed it is a tricky thing to solve automatically: We cannot just add `NetworkSegmentDoubleLinks.run` in `DvrpGlobalRoutingNetworkProvider` for instance, because then the network gets modified and we will have links in the routing network that don't exist in the QSim network, so agents will be stuck. In a standard scenario, this really needs to be cleaned downstream before loading the network.

**Review by michalmac — APPROVED** [review]
Great to have this check!

**Comment by michalmac** [comment]
> Actually, it might make sense to move this further upstream, what do you think @michalmac? The closest `public` access point to this seems to be `OneToManyPathSearch.createSearch`. However, to avoid multiple verifications in DRT, it would probably make sense to have the check in `MultiInsertionDetourPathCalculator`, but then individual users of the class won't see the warning.

IMO it's a good place, because the check is close to the actual functionality that may be affected by this issue.

**Pull request merged**
