### PR TITLE
Configurable mode for travel time validation

### PR DESCRIPTION
**Pull request by rakow**
The TravelTimeValidator now accepts two mode options: One for the mode of the MATSim trips to validate and one for the routing mode to be used in the API.
E.g. this allows to also validate bike trips.

### CODE REVIEW

**Review by luchengqi7 — APPROVED** [review]
Maybe we can change the default date of the HERE API to a working day? (TravelTimeAnalysis, line 174)

**Comment by rakow** [comment]
Why is not using the configured date, but hardcoded ?

**Comment by luchengqi7** [comment]
> Why is not using the configured date, but hardcoded ?

I mean the default value. When the user forget to input the data then default value will be used. And for HERE API it would be nice to have a working day perhaps? But it's not that important...

**Comment by rakow** [comment]
Ok, I have changed it. But in the Line you mentioned it was not using the user input but a fixed value.

**Comment by luchengqi7** [comment]
> Ok, I have changed it. But in the Line you mentioned it was not using the user input but a fixed value.

Oh, I see. Emm, it seems that something was changed... Because for Google Map, we can only use a date in the future (therefore, I remember I set the default date to the same day in the next week). For HERE API, we can only use a date in the past. So A fixed date in the past is used (but I think I set it to some other date instead of 20210101...) Perhapse we can change the default date to the same day in the last week... 

I can do that.

**Comment by rakow** [comment]
Ok, I didn't know that. I changed the default now to depend on the API which was selected.

**Pull request merged**
