### PR TITLE
Update trigger for DTD deployment job.

### PR DESCRIPTION
**Pull request by kt86**
The previous script was never run (which seems to be the cause for #3583), so there seems to be an issue with the triggers:

Therefore I changed the following: 
- Run on merged PRs.
- fix syntax …for target path.

@mrieser : Can you have a look in it, and if ok, merge it? 

And then I assume, we need a PR, changing something in the dtd path, to see, if it works (and updating the ev's dtd at the same time) ... 

Update: I have prepared such a PR: #3586

### CODE REVIEW

**Comment by mrieser** [comment]
I don't have much experience with GitHub actions. Comparing your suggested changes with https://github.com/matsim-org/matsim-libs/blob/master/.github/workflows/deploy-on-pr-merge.yaml I see that the `deploy_on_pr_merge` also has the condition that it is only triggered when merging into `master` branch. Currently, the dtd-deploy would be triggered on ANY merge request. Do we want that?

Otherwise... as I said, I don't have much experience, so it's okay for me. I guess, we'l have to try it out and see what happens.

**Comment by jfbischoff** [comment]
The pipeline is now running, unfortunately something seems wrong with the paths for rsync:

rsync: [sender] change_dir "/github/workspace/matsim/src/main/resources/dtd" failed: No such file or directory (2)

Here is the full log:
https://github.com/matsim-org/matsim-libs/actions/runs/12039650110/job/33567897764

**Comment by jfbischoff** [comment]
I think the path should probably be "/github/workspace/**matsim-libs/**matsim/src/main/resources/dtd

**Comment by kt86** [comment]
> I think the path should probably be "/github/workspace/matsim-libs/matsim/src/main/resources/dtd 

Can you just change it, please? 
Unfortunately I have no idea, with the path information. I am just happy that it has worked to start the pipeline;)

**Comment by kt86** [comment]
Now it works :) 

grafik

The final solution to ass the checkout command as well: #3597

**Pull request merged**
