### PR TITLE
Refactor electric fleet/vehicle specification

### PR DESCRIPTION
**Pull request by michalmac**
Also clean up the ev package inside the vsp contrib (besides the other refactorings in the ev contrib).

### CODE REVIEW

**Comment by tschlenther** [comment]
Thank you really much! Especially for also cleaning up in the vsp-contrib package!!

**Comment by nkuehnel** [comment]
@michalmac will DVRP fleet also be merged in to vehicles?

**Comment by michalmac** [comment]
> @michalmac will DVRP fleet also be merged in to vehicles?

Long-term, yes. However, first I want to see how it works with EVs. I still find it useful to have both `ElectricVehicleSpecification` (esp. due to unit conversions) and `ElectricFleetSpecification` (so we have a known and injectable set of EVs).

**Comment by nkuehnel** [comment]
Alright, thanks!

**Pull request merged**
