### PR TITLE
Added request retry handling

### PR DESCRIPTION
**Pull request by steffenaxer**
A rejected request leads normally directly to a stuckAndAbort event. This pull request allows to collect rejected requests and reinsert them into the passenger engine after waiting for a certain time interval (retryInveral). If the maximum age of a request is exceeded (maxRequestAge), the request is thrown away and causes a  stuckAndAbort event. Functionality is controlled by the help of DvrpRequestRetryParams

### CODE REVIEW

**Comment by sebhoerl** [comment]
I think this is again a case where Travis does not run because the PR comes from a fork. Not sure what was the conclusion last time? :)

**Comment by steffenaxer** [comment]
This configuration of matsim-libs might be the problem?
https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829

**Comment by mrieser** [comment]
MATSim has this option enabled:
matsim-libs-travis

And I think it is an option that we want enabled to keep the master branch in a good state. The [link mentioned above](https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829) states "or Enable Travis CI for your fork", so it looks as if Travis does not run jobs on branches from forks, but they have to be run on the forks separately.

So, (1) either enable Jenkins on your fork, or (2) some matsim-committer could check out the fork and push the branch as new branch to the matsim-repository, and then open a new PR for that branch. (2) would be fine if the PR does not need additional changes, as at least the original author would not have rights to commit further changes to the branch in the MATSim repository. If there will be repeated PRs from one fork, we might also decide to give the person write-permissions to the MATSim repository to simplify things for the future.

**Comment by steffenaxer** [comment]
I already enabled "Travis CI" for my fork and initiated a build for the PR. Sorry, I'm not so familiar with these Travis component. I will check, whether I can do something more...

**Comment by steffenaxer** [comment]
I will try to re-create a new pull request with this enabled Travis CI...

**Pull request closed without merging**
