### PR TITLE
writing and reading persons vehicles attributes from XML

### PR DESCRIPTION
**Pull request by Nitnelav**
an attempt to bring a solution to https://github.com/matsim-org/matsim-libs/issues/1916

### CODE REVIEW

**Comment by sebhoerl** [comment]
:+1: Any objections to that?

The only thing I see is that with population files we then often have incompatibilities in running projects. Can we have a `@Deprecated` fallback that detects whether the attribute is a `Map<String, String>` and then converts it to `PersonVehicles` before processing it?

**Comment by Nitnelav** [comment]
I'm 99.99% sure the attribute `vehicles`, previous to this patch, could not be anything else than a `Map<String, Id<Vehicle>>` , and so was never written to (or red from) any population XML file.
And as I kept the `VehicleUtils.insertVehicleIdsIntoAttributes()` usage the same, I actually don't think there is anything to depreciate. Am I missing something ?

**Comment by Janekdererste** [comment]
>  was never written to (or red from) any population XML file

My guess would be that you are the first who deemded to use this feature. 

Recently we were leaning towards removing automagic. Maybe it is sufficient to crash when the cast to ```PeronsVehicles``` failes.

**Comment by sebhoerl** [comment]
Ah yes, so the xml's in the unit tests were just to compare the output format, right? So I guess this is fine then

**Comment by Nitnelav** [comment]
Yes indeed, the vehicles are always exported in XML now as they are assigned by default, that's why I had to update some tests that rely on comparing the desired pop.xml file with a reference one.

**Comment by Nitnelav** [comment]
We've been updating this PR branch for a while now, nothing new since the last 12 days, can you merge it ?

**Comment by Nitnelav** [comment]
No worries, I can check that on my todo list now, cheers.

**Pull request merged**
