### PR TITLE
default value of the extension search radius is now 0.0

### PR DESCRIPTION
**Pull request by balacmi**
This pull request:

- changes the default value of the extension search radius in SRR to 0 from negative infinity
- adds the default value in the config parameter description
- changes the config consistency check, to allow 0.0 value, and requires the value to be non-negative instead of larger than zero.

### CODE REVIEW

**Comment by vsp-gleich** [comment]
Thanks for this pull request to resolve #1482 . The new default value of 0 is what we accepted in #1482.

I am not sure why you changed the config comment and the config consistency checker though. For most people search extension radius should be > 0. For those few who want to limit the search radius to the initial search radius for whatever reason there is still the option to do this using maxRadius. I would rather suggest keeping the config consistency checker as is and setting a config comment such as "It is strongly reccomended to use a search extension radius larger than 0, e.g. for walk something like 300m".

**Comment by balacmi** [comment]
In my opinion the default value should ensure that the other behavior is maintained i.e., that at least one transit stop is provided to the router. This is ensured with the value of 0.0. 

It is then up to the user to define a non-negative extension search radius if they think that more than one stop should be found within a larger search area. Otherwise, the default behavior does not exist and the user is forced to provide a value.

**Comment by vsp-gleich** [comment]
Obviously nobody else has an opinion on this. Our long term default on search extension radius can be found in [TransitRouterConfig](https://github.com/matsim-org/matsim-libs/blob/fc97a437f52e4c23d50935e8ea6790e2bfbe10e8/matsim/src/main/java/org/matsim/pt/router/TransitRouterConfig.java#L50-L60). I think we have to enforce a value > 0 using the config consistency checker, since 0 has no sense and can even be emulated using maxRadius. The decision is then whether we want a default value which somehow works for all modes such as 200m or 300m or whether we force the user to think about this value and set a default value not accepted by the config consistency checker (0m). A 300m default is less bad than 0 and for modes which work better with a higher extension radius it is maybe more of a performance loss (look for stops in 1000m, 1300m, 1600m, and then 1900m instead of 1000m, then 2000m) than an unacceptable change in result if we assume finding at least 2 stops is all we want (we might find only 2 stops in 1900m, but 4 stops in 2000m).

**Comment by balacmi** [comment]
Fine, I can revert the consistency checker to 0 and add a default value of 200m. Would this be ok for you? I am not so much concerned about this as it is really a minor thing.

**Comment by vsp-gleich** [comment]
Yes, I am ok with > 0 enforced by consistency checker and a default of 200m

**Pull request merged**
